create database supplier;
use supplier;
create table supplier(sid varchar(20),sname varchar(20),city varchar(20),primary key(sid));
drop table supplier;
insert into supplier values('1000','omar','delhi');
insert into supplier values('1001','varun','mangalore');
insert into supplier values('1002','rohan','bangalore');
insert into supplier values('1003','ram','goa');
insert into supplier values('1004','tom','kerela');
select * from supplier;
create table parts(pid varchar(20),pname varchar(20),color varchar(20),primary key(pid));
insert into parts values('2000','charger','pink');
insert into parts values('2001','book','red');
insert into parts values('2002','pencil','green');
insert into parts values('2003','pen','red');
insert into parts values('2004','phone','blue');

create table catalog(sid varchar(20),pid varchar(20),primary key(sid,pid),foreign key(sid)references supplier(sid),foreign key(pid)references parts(pid) on delete cascade);
alter table catalog add cost varchar(20);
select * from catalog;
insert into catalog values('1000','2000','10');
insert into catalog values('1001','2001','20');
insert into catalog values('1002','2002','10');
insert into catalog values('1003','2003','30');
insert into catalog values('1004','2004','50');
select distinct p.pname from parts p,catalog c where p.pid=c.pid;
select s.sname from supplier s where not exists((select p.pid from parts p where (select c.pid from catalog c where c.sid=s.sid)));
select p.pid,s.sname from parts p,supplier s ,catalog c where c.pid=p.pid and c.sid=s.sid and c.cost=(select max(c1.cost)from catalog c1 where(c.pid=p.pid));
select c.sid from catalog c where c.cost>(select avg(cost) from catalog );
select avg(c1.cost) from catalog c1;
select sname from supplier where sid in(select sid from catalog group by sid having count(*))>=(select count(*) from parts where color='red');
select sname from catalog c,parts p where c.pid=p.pid and color='red' group by sid having color='red';